=== Arghali123/Web-Technology/Unit3/DTD/dtd/ExternalDTD_parameters.dtd
<!ELEMENT notes(note+)>
<!ELEMENT notes(to+,from,subject,(message | body)?)
<!ELEMENT to(#PCDATA)>
<!ELEMENT from(#PCDATA)>
<!ELEMENT subject(#PCDATA)>
<!ELEMENT message(#PCDATA)>
<!ELEMENT body(#PCDATA)>
<!ATTLIST note type CDATA #REQUIRED>

=== Arghali123/Web-Technology/Unit3/DTD/dtd/ExternalDTD_parameters.xml
<?xml version="1.0" encoding="UTF=8"?>
<!DOCTYPE notes SYSTEM "ExternalDTD_parameters.dtd">
<notes>
  <note type="sms">
    <to>Ramesh</to>
    <from>Krishna</from>
    <subject>This is my first XML</subject>
    <message>This is my first message from XML</message>
  </note>

  <note type="email">
    <to>Sita</to>
    <to>Ramesh</to>
    <from>Gita</from>
    <subject>This is my second XML</subject>
    <body>This is my second XML message</body>
  </note>
</notes>
